### PR TITLE
WIP - Build XCHammer with XCHammer

### PR DESCRIPTION
**Pull request by rahul-malik**
Still needs work to complete but has a few fixes necessary like
- Swift version support 
- Swift Copts support
- Removing dependencies on XcodeGen setting presets (we should be explicit here)
- Fixing paths to external libraries

There is still an issue I'm hitting with genrule'd files in external libraries that seems to be causing an exception which is blocking progress atm.

### CODE REVIEW

**Comment by rahul-malik** [comment]
```
--- EXCEPTION ---
swiftException(Sources.Generator.GenerateError.some(Error Domain=NSCocoaErrorDomain Code=260 "The folder “BUILD” doesn’t exist." UserInfo={NSFilePath=/Users/rmalik/dev/xchammer/bazel-xchammer/external/xchammer-Tulsi/src/TulsiGenerator/Bazel/tulsi/BUILD, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fd42b43cc90 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}))
The operation couldn’t be completed. (Sources.CommandError error 0.)
------
```

**Comment by jerrymarino** [comment]
@rahul-malik - I think we should consider breaking this PR up into a a few things. It'd be good to  test / isolate each issue that this is addressing individually:
- https://github.com/pinterest/xchammer/issues/11
- https://github.com/pinterest/xchammer/issues/72

Also, I think this may fix a subset of https://github.com/pinterest/xchammer/issues/70

**Comment by rahul-malik** [comment]
Yeah I'll break it up, mostly put this up if someone else wanted to merge parts of it

**Comment by rahul-malik** [comment]
Closing in favor of other PRs that have landed

**Pull request closed without merging**
