### PR TITLE
Use Whole Module Optimization for XCHammer bazel build until persiste…

### PR DESCRIPTION
**Pull request by rahul-malik**
…nt worker is available

Addresses https://github.com/pinterest/xchammer/issues/108

### CODE REVIEW

**Comment by jerrymarino** [comment]
Curious about how this impacts build times and debugging for dev builds - any data points? Also, have you considered moving this into a bazelrc as a config opt? That way, it should apply to all deps and people can choose to set it..

For dev build speed, I’d suggest considering simpler workarounds to fix incremental builds - is that possible?

**Comment by jerrymarino** [comment]
BTW - it seems like settting this breaks incremental builds in Xcode since we set this on OTHER_SWIFT_FLAGS?

**Comment by rahul-malik** [comment]
Actually what do you think about being able to specify a bazelrc file in xchammer yaml config? Might be useful for a ton of things, including this

**Comment by jerrymarino** [comment]
@rahul-malik - that sounds good to me! The way to set a custom bazelrc in Bazel and XCHammer is via provided startup options.  I'd suggest locally setting up a custom bazelrc with options you'd like and then specifying that bazelrc in custom [XCHammerConfig](https://github.com/pinterest/xchammer/blob/master/Sources/XCHammer/XCHammerConfig.swift).

@keith  I'm not so familiar with the workers yet. The plan is to deprecate SPM for XCHammer soon, so definitely looking into this  🎉

**Pull request closed without merging**
