### PR TITLE
Use Swift stub file for targets with zero files and swift dependencies

### PR DESCRIPTION
**Pull request by rahul-malik**
- Adds new asset (Stub.swift)
- Should apply only to targets with swift dependencies
- Fixes swift sample project (Tailor)

### CODE REVIEW

**Comment by kastiglione** [comment]
What targets would have zero files

**Comment by jerrymarino** [comment]
@kastiglione the common example is, "bundle" like Apple app targets.

These rules may have sources in `*_library`'s deps. At build time, bazel creates targets to links them all together ( i.e. how `ios_application` works )
```
ios_application(deps=[":a"])

objc_library(name="a", srcs=["main.c"])
```
So, under XCHammer, we end up with empty `ios_application`'s. Since Xcode predicates creating a `.swiftmodule` on the presence of a `.swift` file, the build won't work without it.

**Comment by kastiglione** [comment]
So it's only the case for certain rules, like ios_application?

**Comment by rahul-malik** [comment]
@kastiglione - Yup. Since top-level targets contain their sources in library / framework dependencies they have zero source and need a dummy file.

**Pull request merged**
