### PR TITLE
Small fix to adjust README to current usage

### PR DESCRIPTION
**Pull request by thiagohmcruz**
Small fix for something that I've found while setting up!

### CODE REVIEW

**Review by jerrymarino — APPROVED** [review]
@thiagohmcruz nice fix 👍

**Comment by thiagohmcruz** [comment]
`make_test` ir 🔴 
```sh
** BUILD FAILED **


The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/UrlGet-bpmcgcgbjwtltrefwwmtlvtvdoey/Build/Intermediates.noindex/UrlGet.build/Debug-iphonesimulator/ios-app.build/Objects-normal/arm64/Binary/ios-app normal arm64
```
trying to repro locally

**Comment by jerrymarino** [comment]
@thiagohmcruz LGTM think the CI just flaked we can fix that here shortly 🏃‍♀️

**Comment by thiagohmcruz** [comment]
Missed the fact that there was an issue for that #297, I'll resolve it

**Pull request merged**
