### PR TITLE
Compose deployment target settings on Bazel Target

### PR DESCRIPTION
**Pull request by jerrymarino**
Prior, we expected this to be set by `SettingsPresests`.

### CODE REVIEW

**Comment by rahul-malik** [comment]
@jerrymarino - Did you intend for this to be two separate commits? The diagnostics and deployment target seem like unrelated changes

**Comment by jerrymarino** [comment]
There's another PR that this one is sitting ontop of, so I think once that lands, it should rebase. I'm not sure if the CI is blocked because of the Bazel target regression from `SettingsPresets`..

**Comment by jerrymarino** [comment]
https://travis-ci.org/pinterest/xchammer/builds/446876386?utm_source=github_status&utm_medium=notification

**Comment by jerrymarino** [comment]
It does fix the issue @rahul-malik - I can't believe that the other PR passed!

**Pull request merged**
